version: '3'
services:
  web:
    build: ./composetest
    ports:
      - "80:5000"
    volumes:
      - ./composetest:/code
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"