version: '3'
services:
  web:
    build: ./composetest
    ports:
      - "80:5000"
    volumes:
      - ./composetest:/code
    environment:
      FLASK_ENV: development
    networks:
      - backend
      - frontend
  redis:
    image: "redis:alpine"
    networks:  
      - backend
    

networks:
  frontend:
  backend: