FROM python:3.9-alpine

RUN apk update && apk add curl

ADD . /code
WORKDIR /code
RUN pip install -r requirements.txt

ENV RND_API_HOST_AND_PORT=rnd-api:5000

CMD curl --fail http://rnd-api-health/rng && \
    python app.py
