apiVersion: v1
kind: Pod
metadata:
  name: myapp-startup-probe
spec:
  containers:
  - name: myapp
    image: leon11sj/test-app
    ports:
    - name: http
      containerPort: 8080
    startupProbe:
      httpGet:
        path: /
        port: http
      periodSeconds: 10
      failureThreshold:  12
    livenessProbe:
      httpGet:
        path: /
        port: http
      periodSeconds: 5
      failureThreshold: 2
  - name: envoy
    image: leon11sj/myapp-ssl-proxy:1.2
    ports:
    - name: https
      containerPort: 8443
    - name: admin
      containerPort: 9901
    livenessProbe:
      httpGet:
        path: /ready
        port: admin
      initialDelaySeconds: 10
      periodSeconds: 3
      timeoutSeconds: 2
      failureThreshold: 5
