apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
spec:
  type: ClusterIP
  ports:
  - name: myapp-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc
  selector:
    app: myapp
    zone: prod
    version: v1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
        zone: prod
        version: v1
    spec:
      containers:
      - name: myapp
        image: leon11sj/test-app
        ports:
        - containerPort: 8080
          name: http-web-svc


