version: "3.7"

services:
  rnd-api-health:
    image: random-number-api-health
    ports:
      - "8080:5000"
    healthcheck:
      interval: 5s
      timeout: 1s
      retries: 2
      start_period: 5s
    networks:
      - app-net

  numbers-web:
    image: random-number-web-check
    restart: on-failure
    environment:
      - RND_API_HOST_AND_PORT=rnd-api-health:5000
    ports:
      - "80:5000"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/health"]
      interval: 5s
      timeout: 1s
      retries: 2
      start_period: 10s
    networks:
      - app-net

networks:
  app-net:
