apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-web
spec:
  selector:
    matchLabels:
      app: todo-web
  template:
    metadata:
      labels:
        app: todo-web
    spec:
      containers:
        - name: web
          image: leon11sj/todo-list
          volumeMounts: # Mounts a volume into the container
            - name: config  # Names the volume
              mountPath: "/app/config"  # Directory path to mount the volume
              readOnly: true  # Flags the volume as read-only
      volumes:
        - name: config # Volumes are defined at the Pod level. Name matches the volume mount.
          configMap:  # Volume source is a ConfigMap. 
            name: todo-web-config-dev  # ConfigMap name
