version: "3.8"
services:
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:8080
    depends_on:
      - web-fe
    networks:
      - frontend
  web-fe:
    image: leon11sj/counter
    entrypoint: ["gunicorn", "--bind", "0.0.0.0:5000", "wsgi:app"]
    networks:
      - backend
      - frontend
    depends_on:
      - redis
    environment:
      FLASK_DEBUG: "true"
  redis:
    image: "redis:alpine"
    networks:
      - backend
    volumes:
      - "redis-data:/data"

networks:
  backend:
  frontend:

volumes:
  redis-data:
