apiVersion: v1
kind: Pod
metadata:
  name: myapp-ssl
spec:
  containers:
  - name: myapp 
    image: leon11sj/test-app
    ports: 
    - name: http 
      containerPort: 8080
  - name: envoy 
    image: leon11sj/myapp-ssl-proxy:1.2
    ports:
    - name: https
      containerPort: 8443
    - name: admin 
      containerPort: 9901
