apiVersion: v1
kind: Pod
metadata:
  name: myapp-init
spec:
  initContainers:
  - name: init-demo
    image: leon11sj/init-demo:1.0
    imagePullPolicy: Always
  - name: network-check
    image: leon11sj/network-checker:1.0
    imagePullPolicy: Always
  containers: 
  - name: myapp 
    image: leon11sj/test-app
    imagePullPolicy: Always
    ports: 
    - name: http 
      containerPort: 8080 
  - name: envoy 
    image: leon11sj/myapp-ssl-proxy:1.2
    imagePullPolicy: Always
    ports: 
    - name: https 
      containerPort: 8443 
    - name: admin 
      containerPort: 9901